2015-03-06 18:41:37,464  ERROR:hf.module.ModuleProxy(ddm_datasets_viewer)  /var/lib/HappyFace3/hf/module/ModuleProxy.py:148  Data extraction failed: list index out of range
2015-03-06 18:41:37,467  ERROR:hf.module.ModuleProxy(ddm_datasets_viewer)  /var/lib/HappyFace3/hf/module/ModuleProxy.py:149  Traceback (most recent call last):
  File "/var/lib/HappyFace3/hf/module/ModuleProxy.py", line 102, in acquire
    d = module.extractData()
  File "/var/lib/HappyFace3/modules/DdmDatasetsViewer.py", line 58, in extractData
    DataObject.run('GOEGRID_LOCALGROUPDISK')
  File "/var/lib/HappyFace3/hf/gridtoolkit/DdmDatasetsController.py", line 203, in run
    listOfDatasets = self.limited(token)
  File "/var/lib/HappyFace3/hf/gridtoolkit/DdmDatasetsController.py", line 229, in limited
    shortlistOfDatasets.append(datasets[x])
IndexError: list index out of range

2015-03-06 18:42:52,720  ERROR:hf.module.ModuleProxy(grid_ftp)  /var/lib/HappyFace3/hf/module/ModuleProxy.py:148  Data extraction failed: rmFile() takes exactly 3 arguments (4 given)
2015-03-06 18:42:52,722  ERROR:hf.module.ModuleProxy(grid_ftp)  /var/lib/HappyFace3/hf/module/ModuleProxy.py:149  Traceback (most recent call last):
  File "/var/lib/HappyFace3/hf/module/ModuleProxy.py", line 102, in acquire
    d = module.extractData()
  File "/var/lib/HappyFace3/modules/GridFtpCopyViewer.py", line 164, in extractData
    dataDiskPathSite1)
  File "/var/lib/HappyFace3/modules/GridFtpCopyViewer.py", line 75, in spaceTokenStatus
    Object.rmFile(srcHost , fileName_scr, srcPath_scr)
TypeError: rmFile() takes exactly 3 arguments (4 given)

2015-03-20 17:19:19,783  ERROR:hf.module.ModuleProxy(grid_ftp)  /var/lib/HappyFace3/hf/module/ModuleProxy.py:148  Data extraction failed: Required parameter 'site1_port' not specified
2015-03-20 17:19:19,794  ERROR:hf.module.ModuleProxy(grid_ftp)  /var/lib/HappyFace3/hf/module/ModuleProxy.py:149  Traceback (most recent call last):
  File "/var/lib/HappyFace3/hf/module/ModuleProxy.py", line 102, in acquire
    d = module.extractData()
  File "/var/lib/HappyFace3/modules/GridFtpCopyViewer.py", line 143, in extractData
    transfer_obj.setSrcPort(self.config['site1_port'])
  File "/var/lib/HappyFace3/hf/configtools.py", line 69, in __getitem__
    raise hf.ConfigError("Required parameter '{0}' not specified".format(key))
ConfigError: Required parameter 'site1_port' not specified

2015-03-20 17:24:21,938  ERROR:hf.module.ModuleProxy(grid_ftp)  /var/lib/HappyFace3/hf/module/ModuleProxy.py:148  Data extraction failed: Required parameter 'site1_port' not specified
2015-03-20 17:24:21,940  ERROR:hf.module.ModuleProxy(grid_ftp)  /var/lib/HappyFace3/hf/module/ModuleProxy.py:149  Traceback (most recent call last):
  File "/var/lib/HappyFace3/hf/module/ModuleProxy.py", line 102, in acquire
    d = module.extractData()
  File "/var/lib/HappyFace3/modules/GridFtpCopyViewer.py", line 143, in extractData
    transfer_obj.setSrcPort(self.config['site1_port'])
  File "/var/lib/HappyFace3/hf/configtools.py", line 69, in __getitem__
    raise hf.ConfigError("Required parameter '{0}' not specified".format(key))
ConfigError: Required parameter 'site1_port' not specified

2015-03-20 17:25:13,803  ERROR:hf.module.ModuleProxy(grid_ftp)  /var/lib/HappyFace3/hf/module/ModuleProxy.py:148  Data extraction failed: 'ProdDisk' object has no attribute 'setLocalGroupDisk'
2015-03-20 17:25:13,804  ERROR:hf.module.ModuleProxy(grid_ftp)  /var/lib/HappyFace3/hf/module/ModuleProxy.py:149  Traceback (most recent call last):
  File "/var/lib/HappyFace3/hf/module/ModuleProxy.py", line 102, in acquire
    d = module.extractData()
  File "/var/lib/HappyFace3/modules/GridFtpCopyViewer.py", line 157, in extractData
    prodDisk_obj.setLocalGroupDisk("ProdDisk")
AttributeError: 'ProdDisk' object has no attribute 'setLocalGroupDisk'

2015-03-20 17:25:59,616  ERROR:hf.downloadservice  /var/lib/HappyFace3/hf/downloadservice.py:87  Cannot create archive directory
2015-03-20 17:25:59,625  ERROR:hf.downloadservice  /var/lib/HappyFace3/hf/downloadservice.py:88  Traceback (most recent call last):
  File "/var/lib/HappyFace3/hf/downloadservice.py", line 85, in performDownloads
    os.makedirs(self.archive_dir)
  File "/usr/lib64/python2.6/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: 'static/archive/2015/03/20/17/25'

2015-03-20 17:25:59,625  WARNING:__main__  grid_enabled_acquire.py:95  Downloading of all files failed
2015-03-20 17:25:59,626  ERROR:hf.module.ModuleProxy(grid_ftp)  /var/lib/HappyFace3/hf/module/ModuleProxy.py:148  Data extraction failed: 'DataDisk' object has no attribute 'setLocalGroupDisk'
2015-03-20 17:25:59,627  ERROR:hf.module.ModuleProxy(grid_ftp)  /var/lib/HappyFace3/hf/module/ModuleProxy.py:149  Traceback (most recent call last):
  File "/var/lib/HappyFace3/hf/module/ModuleProxy.py", line 102, in acquire
    d = module.extractData()
  File "/var/lib/HappyFace3/modules/GridFtpCopyViewer.py", line 161, in extractData
    dataDisk_obj.setLocalGroupDisk("DataDisk")
AttributeError: 'DataDisk' object has no attribute 'setLocalGroupDisk'

2015-03-20 17:26:24,418  ERROR:hf.module.ModuleProxy(grid_ftp)  /var/lib/HappyFace3/hf/module/ModuleProxy.py:148  Data extraction failed: cannot concatenate 'str' and 'NoneType' objects
2015-03-20 17:26:24,420  ERROR:hf.module.ModuleProxy(grid_ftp)  /var/lib/HappyFace3/hf/module/ModuleProxy.py:149  Traceback (most recent call last):
  File "/var/lib/HappyFace3/hf/module/ModuleProxy.py", line 102, in acquire
    d = module.extractData()
  File "/var/lib/HappyFace3/modules/GridFtpCopyViewer.py", line 169, in extractData
    localToRemote_obj.mkDir(transfer_obj.getSrcHost(),scratchdisk_obj.getSpaceTokenPath())
  File "/var/lib/HappyFace3/hf/gridtoolkit/TransferTypes.py", line 69, in mkDir
    self.commandArgs = 'uberftp ' + host + ' "mkdir ' +  dstPath + ' " '
TypeError: cannot concatenate 'str' and 'NoneType' objects

2015-03-20 17:27:23,795  ERROR:hf.module.ModuleProxy(grid_ftp)  /var/lib/HappyFace3/hf/module/ModuleProxy.py:148  Data extraction failed: cannot concatenate 'str' and 'NoneType' objects
2015-03-20 17:27:23,796  ERROR:hf.module.ModuleProxy(grid_ftp)  /var/lib/HappyFace3/hf/module/ModuleProxy.py:149  Traceback (most recent call last):
  File "/var/lib/HappyFace3/hf/module/ModuleProxy.py", line 102, in acquire
    d = module.extractData()
  File "/var/lib/HappyFace3/modules/GridFtpCopyViewer.py", line 171, in extractData
    localToRemote_obj.mkDir(transfer_obj.getSrcHost(),scratchdisk_obj.getSpaceTokenPath())
  File "/var/lib/HappyFace3/hf/gridtoolkit/TransferTypes.py", line 69, in mkDir
    self.commandArgs = 'uberftp ' + host + ' "mkdir ' +  dstPath + ' " '
TypeError: cannot concatenate 'str' and 'NoneType' objects

2015-03-20 17:31:43,459  ERROR:hf.module.ModuleProxy(grid_ftp)  /var/lib/HappyFace3/hf/module/ModuleProxy.py:148  Data extraction failed: cannot concatenate 'str' and 'NoneType' objects
2015-03-20 17:31:43,460  ERROR:hf.module.ModuleProxy(grid_ftp)  /var/lib/HappyFace3/hf/module/ModuleProxy.py:149  Traceback (most recent call last):
  File "/var/lib/HappyFace3/hf/module/ModuleProxy.py", line 102, in acquire
    d = module.extractData()
  File "/var/lib/HappyFace3/modules/GridFtpCopyViewer.py", line 173, in extractData
    localToRemote_obj.mkDir(transfer_obj.getSrcHost(),scratchdisk_obj.getSpaceTokenPath())
  File "/var/lib/HappyFace3/hf/gridtoolkit/TransferTypes.py", line 69, in mkDir
    self.commandArgs = 'uberftp ' + host + ' "mkdir ' +  dstPath + ' " '
TypeError: cannot concatenate 'str' and 'NoneType' objects

2015-03-20 17:35:19,530  ERROR:hf.module.ModuleProxy(grid_ftp)  /var/lib/HappyFace3/hf/module/ModuleProxy.py:148  Data extraction failed: cannot concatenate 'str' and 'NoneType' objects
2015-03-20 17:35:19,531  ERROR:hf.module.ModuleProxy(grid_ftp)  /var/lib/HappyFace3/hf/module/ModuleProxy.py:149  Traceback (most recent call last):
  File "/var/lib/HappyFace3/hf/module/ModuleProxy.py", line 102, in acquire
    d = module.extractData()
  File "/var/lib/HappyFace3/modules/GridFtpCopyViewer.py", line 173, in extractData
    localToRemote_obj.mkDir(transfer_obj.getSrcHost(),scratchdisk_obj.getSpaceTokenPath())
  File "/var/lib/HappyFace3/hf/gridtoolkit/TransferTypes.py", line 69, in mkDir
    self.commandArgs = 'uberftp ' + host + ' "mkdir ' +  dstPath + ' " '
TypeError: cannot concatenate 'str' and 'NoneType' objects

2015-03-20 17:38:45,571  ERROR:hf.module.ModuleProxy(grid_ftp)  /var/lib/HappyFace3/hf/module/ModuleProxy.py:148  Data extraction failed: cannot concatenate 'str' and 'NoneType' objects
2015-03-20 17:38:45,572  ERROR:hf.module.ModuleProxy(grid_ftp)  /var/lib/HappyFace3/hf/module/ModuleProxy.py:149  Traceback (most recent call last):
  File "/var/lib/HappyFace3/hf/module/ModuleProxy.py", line 102, in acquire
    d = module.extractData()
  File "/var/lib/HappyFace3/modules/GridFtpCopyViewer.py", line 173, in extractData
    localToRemote_obj.mkDir(transfer_obj.getSrcHost(),scratchdisk_obj.getSpaceTokenPath())
  File "/var/lib/HappyFace3/hf/gridtoolkit/TransferTypes.py", line 69, in mkDir
    self.commandArgs = 'uberftp ' + host + ' "mkdir ' +  dstPath + ' " '
TypeError: cannot concatenate 'str' and 'NoneType' objects

2015-03-20 17:39:45,266  ERROR:__main__  grid_enabled_acquire.py:64  Setting up HappyFace failed: invalid syntax (GridFtpCopyViewer.py, line 170)
2015-03-20 17:39:45,274  ERROR:__main__  grid_enabled_acquire.py:65  Traceback (most recent call last):
  File "grid_enabled_acquire.py", line 53, in <module>
    hf.module.importModuleClasses()
  File "/var/lib/HappyFace3/hf/module/module.py", line 63, in importModuleClasses
    loader.load_module(name)
  File "/usr/lib64/python2.6/pkgutil.py", line 238, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/var/lib/HappyFace3/modules/GridFtpCopyViewer.py", line 170
    print transfer_obj.getSrcHost())
                                   ^
SyntaxError: invalid syntax

2015-03-20 17:40:03,394  ERROR:hf.module.ModuleProxy(grid_ftp)  /var/lib/HappyFace3/hf/module/ModuleProxy.py:148  Data extraction failed: cannot concatenate 'str' and 'NoneType' objects
2015-03-20 17:40:03,394  ERROR:hf.module.ModuleProxy(grid_ftp)  /var/lib/HappyFace3/hf/module/ModuleProxy.py:149  Traceback (most recent call last):
  File "/var/lib/HappyFace3/hf/module/ModuleProxy.py", line 102, in acquire
    d = module.extractData()
  File "/var/lib/HappyFace3/modules/GridFtpCopyViewer.py", line 175, in extractData
    localToRemote_obj.copying(transfer_obj.getSrcHost(),scratchdisk_obj.getSpaceTokenPath())
  File "/var/lib/HappyFace3/hf/gridtoolkit/TransferTypes.py", line 82, in copying
    copyStatus, stderr, srcPath, fileName = self.createFileInSrcPath(host, path)
  File "/var/lib/HappyFace3/hf/gridtoolkit/TransferTypes.py", line 90, in createFileInSrcPath
    stdout, stderr = self.copyFormLocalToRemote(host, localPath, path)
  File "/var/lib/HappyFace3/hf/gridtoolkit/TransferTypes.py", line 98, in copyFormLocalToRemote
    self.commandArgs = 'uberftp ' + srcHost + '  "put ' + localPath + "  " + srcPath + ' "'
TypeError: cannot concatenate 'str' and 'NoneType' objects

2015-03-23 13:04:40,215  ERROR:hf.category.CategoryProxy(grid_FTP)  /var/lib/HappyFace3/hf/category/CategoryProxy.py:57  Cannot add module instance grid_ftp: Module class GridFtpViewer not found
2015-03-23 13:04:40,276  ERROR:hf.category.CategoryProxy(grid_FTP)  /var/lib/HappyFace3/hf/category/CategoryProxy.py:58  Traceback (most recent call last):
  File "/var/lib/HappyFace3/hf/category/CategoryProxy.py", line 53, in __init__
    hf.module.getModuleClass(cfg["module"])
  File "/var/lib/HappyFace3/hf/module/module.py", line 77, in getModuleClass
    raise hf.ConfigError("Module class {0} not found".format(mod_name))
ConfigError: Module class GridFtpViewer not found

2015-03-23 13:05:07,014  ERROR:hf.category.CategoryProxy(grid_FTP)  /var/lib/HappyFace3/hf/category/CategoryProxy.py:57  Cannot add module instance grid_ftp: Module class GridFtpViewer not found
2015-03-23 13:05:07,014  ERROR:hf.category.CategoryProxy(grid_FTP)  /var/lib/HappyFace3/hf/category/CategoryProxy.py:58  Traceback (most recent call last):
  File "/var/lib/HappyFace3/hf/category/CategoryProxy.py", line 53, in __init__
    hf.module.getModuleClass(cfg["module"])
  File "/var/lib/HappyFace3/hf/module/module.py", line 77, in getModuleClass
    raise hf.ConfigError("Module class {0} not found".format(mod_name))
ConfigError: Module class GridFtpViewer not found

2015-03-23 13:05:20,232  ERROR:hf.category.CategoryProxy(grid_FTP)  /var/lib/HappyFace3/hf/category/CategoryProxy.py:57  Cannot add module instance grid_ftp: Module class GridFtpViewer not found
2015-03-23 13:05:20,232  ERROR:hf.category.CategoryProxy(grid_FTP)  /var/lib/HappyFace3/hf/category/CategoryProxy.py:58  Traceback (most recent call last):
  File "/var/lib/HappyFace3/hf/category/CategoryProxy.py", line 53, in __init__
    hf.module.getModuleClass(cfg["module"])
  File "/var/lib/HappyFace3/hf/module/module.py", line 77, in getModuleClass
    raise hf.ConfigError("Module class {0} not found".format(mod_name))
ConfigError: Module class GridFtpViewer not found

2015-03-23 13:05:27,426  ERROR:hf.downloadservice  /var/lib/HappyFace3/hf/downloadservice.py:87  Cannot create archive directory
2015-03-23 13:05:27,443  ERROR:hf.downloadservice  /var/lib/HappyFace3/hf/downloadservice.py:88  Traceback (most recent call last):
  File "/var/lib/HappyFace3/hf/downloadservice.py", line 85, in performDownloads
    os.makedirs(self.archive_dir)
  File "/usr/lib64/python2.6/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: 'static/archive/2015/03/23/13/05'

2015-03-23 13:05:27,444  WARNING:__main__  grid_enabled_acquire.py:95  Downloading of all files failed
2015-03-23 13:07:12,013  ERROR:hf.category.CategoryProxy(grid_FTP)  /var/lib/HappyFace3/hf/category/CategoryProxy.py:57  Cannot add module instance grid_ftp: Module class GridFtpViewer not found
2015-03-23 13:07:12,013  ERROR:hf.category.CategoryProxy(grid_FTP)  /var/lib/HappyFace3/hf/category/CategoryProxy.py:58  Traceback (most recent call last):
  File "/var/lib/HappyFace3/hf/category/CategoryProxy.py", line 53, in __init__
    hf.module.getModuleClass(cfg["module"])
  File "/var/lib/HappyFace3/hf/module/module.py", line 77, in getModuleClass
    raise hf.ConfigError("Module class {0} not found".format(mod_name))
ConfigError: Module class GridFtpViewer not found

2015-03-23 13:10:02,609  ERROR:hf.category.CategoryProxy(grid_FTP)  /var/lib/HappyFace3/hf/category/CategoryProxy.py:57  Cannot add module instance grid_ftp: Module class GridFtpViewer not found
2015-03-23 13:10:02,610  ERROR:hf.category.CategoryProxy(grid_FTP)  /var/lib/HappyFace3/hf/category/CategoryProxy.py:58  Traceback (most recent call last):
  File "/var/lib/HappyFace3/hf/category/CategoryProxy.py", line 53, in __init__
    hf.module.getModuleClass(cfg["module"])
  File "/var/lib/HappyFace3/hf/module/module.py", line 77, in getModuleClass
    raise hf.ConfigError("Module class {0} not found".format(mod_name))
ConfigError: Module class GridFtpViewer not found

2015-03-23 13:11:45,809  ERROR:hf.module.ModuleProxy(ddm_datasets_viewer)  /var/lib/HappyFace3/hf/module/ModuleProxy.py:148  Data extraction failed: list index out of range
2015-03-23 13:11:45,809  ERROR:hf.module.ModuleProxy(ddm_datasets_viewer)  /var/lib/HappyFace3/hf/module/ModuleProxy.py:149  Traceback (most recent call last):
  File "/var/lib/HappyFace3/hf/module/ModuleProxy.py", line 102, in acquire
    d = module.extractData()
  File "/var/lib/HappyFace3/modules/DdmDatasetsViewer.py", line 58, in extractData
    DataObject.run('GOEGRID_LOCALGROUPDISK')
  File "/var/lib/HappyFace3/hf/gridtoolkit/DdmDatasetsController.py", line 203, in run
    listOfDatasets = self.limited(token)
  File "/var/lib/HappyFace3/hf/gridtoolkit/DdmDatasetsController.py", line 229, in limited
    shortlistOfDatasets.append(datasets[x])
IndexError: list index out of range

2015-03-23 13:13:54,036  ERROR:hf.category.CategoryProxy(grid_FTP)  /var/lib/HappyFace3/hf/category/CategoryProxy.py:57  Cannot add module instance grid_ftp: Module class GridFtpViewer not found
2015-03-23 13:13:54,037  ERROR:hf.category.CategoryProxy(grid_FTP)  /var/lib/HappyFace3/hf/category/CategoryProxy.py:58  Traceback (most recent call last):
  File "/var/lib/HappyFace3/hf/category/CategoryProxy.py", line 53, in __init__
    hf.module.getModuleClass(cfg["module"])
  File "/var/lib/HappyFace3/hf/module/module.py", line 77, in getModuleClass
    raise hf.ConfigError("Module class {0} not found".format(mod_name))
ConfigError: Module class GridFtpViewer not found

2015-03-23 13:15:03,959  ERROR:hf.module.ModuleProxy(ddm_datasets_viewer)  /var/lib/HappyFace3/hf/module/ModuleProxy.py:148  Data extraction failed: list index out of range
2015-03-23 13:15:03,960  ERROR:hf.module.ModuleProxy(ddm_datasets_viewer)  /var/lib/HappyFace3/hf/module/ModuleProxy.py:149  Traceback (most recent call last):
  File "/var/lib/HappyFace3/hf/module/ModuleProxy.py", line 102, in acquire
    d = module.extractData()
  File "/var/lib/HappyFace3/modules/DdmDatasetsViewer.py", line 58, in extractData
    DataObject.run('GOEGRID_LOCALGROUPDISK')
  File "/var/lib/HappyFace3/hf/gridtoolkit/DdmDatasetsController.py", line 203, in run
    listOfDatasets = self.limited(token)
  File "/var/lib/HappyFace3/hf/gridtoolkit/DdmDatasetsController.py", line 229, in limited
    shortlistOfDatasets.append(datasets[x])
IndexError: list index out of range

2015-03-23 13:36:11,503  ERROR:hf.module.ModuleProxy(ddm_datasets_viewer)  /var/lib/HappyFace3/hf/module/ModuleProxy.py:148  Data extraction failed: list index out of range
2015-03-23 13:36:11,504  ERROR:hf.module.ModuleProxy(ddm_datasets_viewer)  /var/lib/HappyFace3/hf/module/ModuleProxy.py:149  Traceback (most recent call last):
  File "/var/lib/HappyFace3/hf/module/ModuleProxy.py", line 102, in acquire
    d = module.extractData()
  File "/var/lib/HappyFace3/modules/DdmDatasetsViewer.py", line 58, in extractData
    DataObject.run('GOEGRID_LOCALGROUPDISK')
  File "/var/lib/HappyFace3/hf/gridtoolkit/DdmDatasetsController.py", line 203, in run
    listOfDatasets = self.limited(token)
  File "/var/lib/HappyFace3/hf/gridtoolkit/DdmDatasetsController.py", line 229, in limited
    shortlistOfDatasets.append(datasets[x])
IndexError: list index out of range

2015-03-23 13:36:31,854  ERROR:__main__  grid_enabled_acquire.py:38  Another process is still running
